### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by simonyel** [PhracturedBlue/c6_adc#1]
Full config file: 
```
substitutions:
  device_name: 'solar-station'
  friendly_name: solar-station
  device_comment: "Solar Station 1"
  entity_prefix: "st1"
  device_type: "SVYtech" 

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: "5.3.0"
    platform_version: "6.8.1"
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

esphome:
  platformio_options:
      platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
      board_build.f_cpu: 160000000L
      board_build.f_flash: 80000000L
      board_build.flash_size: 4MB

packages:
  core: !include _config/core_basic.yaml  

external_components:
  - source: github://PhracturedBlue/c6_adc
   #Source is not a file system path, in expected github://username/name[@branch-or-tag] or github://pr#1234 format!.

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "####"

light:
  - platform: esp32_rmt_led_strip
    chipset: SK6812
    rgb_order: GRB
    pin: 
      number: GPIO15
      ignore_strapping_warning: True
    num_leds: 1
    name: "Status LED"
    id: internal_led
    icon: mdi:led-outline    

sensor:
  - platform: adc
    pin: GPIO3
    name: "led25"
    attenuation: 0dB  # optional.  defaults to 12dB
    update_interval: 30s
```
Build Log
```
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.5") 
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /root/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc
-- Check for working C compiler: /root/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc
-- Check for working C compiler: /root/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /root/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++
-- Check for working CXX compiler: /root/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32c6
Dependencies lock doesn't exist, solving dependencies.
.Updating lock file at /root/config/.esphome/build/solar-station/dependencies.lock
Processing 1 dependencies:
[1/1] idf (5.3.0)
-- Project sdkconfig file /root/config/.esphome/build/solar-station/sdkconfig.solar-station
/root/config/.esphome/build/solar-station/sdkconfig.solar-station:1 CONFIG_COMPILER_OPTIMIZATION_DEFAULT was replaced with CONFIG_COMPILER_OPTIMIZATION_DEBUG
/root/config/.esphome/build/solar-station/sdkconfig.solar-station:6 CONFIG_ESP_TASK_WDT was replaced with CONFIG_ESP_TASK_WDT_INIT
-- Configuring incomplete, errors occurred!
See also "/root/config/.esphome/build/solar-station/.pioenvs/solar-station/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at /root/.platformio/packages/framework-espidf/tools/cmake/tool_version_check.cmake:36 (message):
  

  Tool doesn't match supported version from list ['esp-13.2.0_20240530']:
  /root/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc

  Please try to run 'idf.py fullclean' to solve it.

Call Stack (most recent call first):
  /root/.platformio/packages/framework-espidf/components/esp_common/project_include.cmake:10 (check_expected_tool_version)
  /root/.platformio/packages/framework-espidf/tools/cmake/build.cmake:400 (include)
  /root/.platformio/packages/framework-espidf/tools/cmake/build.cmake:632 (__build_process_project_includes)
  /root/.platformio/packages/framework-espidf/tools/cmake/project.cmake:710 (idf_build_process)
  CMakeLists.txt:3 (project)
```
